version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    volumes:
      - '.:/app'
      - 'app-build:/app/_build'
      - 'app-deps:/app/deps'
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg-data:
  app-build:
  app-deps:
