AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/*'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'config.ru'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: 1000

Metrics/ModuleLength:
  Enabled: 1000

Metrics/MethodLength:
  Enabled: 100

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/CaseIndentation:
  EnforcedStyle: end

Rails/HasAndBelongsToMany:
  Enabled: false