default: &default
  adapter: mysql2
  encoding: utf8
  collate: utf8_general_ci
  database: <%= ENV["MYSQL_DATABASE"] || 'desafio-ninja' %>
  username: <%= ENV["MYSQL_ROOT_NAME"] || 'root' %>
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] || 'root' %>
  port: <%= ENV["MYSQL_DB_PORT"] || 3306 %>
  host: <%= ENV["MYSQL_DB_HOST"] || '127.0.0.1' %>
  timeout: 5000

development:
  <<: *default
  database: desafio_ninja_development

test: &test
  <<: *default
  database: desafio_ninja_test

cucumber:
  <<: *test
