default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= Rails.application.credentials.database_url %>
  pool: 30

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
