default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: postgres
  host: <%= ENV['LOCAL'] == 'docker' ? 'db' : 'localhost' %>
  port: 5432

development:
  <<: *default
  database: desafio_getninja_development

test:
  <<: *default
  database: desafio_getninja_test

production:
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  database: desafio_getninja_production
  username: postgres
  host: # host
  password: <%= Rails.application.credentials.config[:database_password] %>
