development:
  clients:
    default:
      database: meeting_rooms_development
      hosts:
        - <%= ENV.fetch('DATABASE_URL') { 'localhost:27017' } %>
      options:
        max_pool_size: 10
        use_activesupport_time_zone: true
staging:
  clients:
    default:
      database: meeting_rooms_staging
      hosts:
        - <%= ENV.fetch('DATABASE_URL') { 'localhost:27017' } %>
      options:
        write:
          w: 1
        raise_not_found_error: false
        max_pool_size: 10
        use_activesupport_time_zone: true
test:
  clients:
    default:
      database: meeting_rooms_test
      hosts:
        - <%= ENV.fetch('DATABASE_URL') { 'localhost:27017' } %>
      options:
        read:
          mode: :primary
        max_pool_size: 10
        use_activesupport_time_zone: true
  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true
